from collections.abc import Awaitable, Callable
from typing import Protocol

from app.models.config import MonitoringConfig
from app.models.hearing import HearingState
from app.models.monitoring import InterventionRecord, JudgmentRecord, SessionState


class ConfigRepository(Protocol):
    async def save(self, config: MonitoringConfig) -> None: ...
    async def get(self, config_id: str) -> MonitoringConfig | None: ...
    async def get_latest(self) -> MonitoringConfig | None: ...


class HearingRepository(Protocol):
    async def save(self, state: HearingState) -> None: ...
    async def get(self, hearing_id: str) -> HearingState | None: ...


class SessionRepository(Protocol):
    async def create(self, session: SessionState) -> None: ...
    async def get(self, session_id: str) -> SessionState | None: ...

    async def update(
        self, session_id: str, mutate: Callable[[SessionState], SessionState]
    ) -> SessionState:
        """セッション本体の read-modify-write。Firestore 実装ではトランザクションで保護する"""
        ...

    async def append_judgment(self, session_id: str, record: JudgmentRecord) -> None: ...
    async def list_judgments(self, session_id: str) -> list[JudgmentRecord]: ...

    async def append_intervention(self, session_id: str, record: InterventionRecord) -> None: ...
    async def update_intervention_result(
        self, session_id: str, intervention_id: str, result: str
    ) -> None: ...
    async def list_interventions(self, session_id: str) -> list[InterventionRecord]: ...


MutateFn = Callable[[SessionState], SessionState | Awaitable[SessionState]]
